### PR TITLE
framework for different analyzers, nextest support

### LINKED ISSUE #196: Synergy with cargo nextest
I find both `bacon` and [`cargo nextest`](https://nexte.st/) to be very useful, and I would like to use them together.

I can persuade `bacon` to run tests via `cargo nextest` by specifying this in `bacon.toml`:

```toml

[jobs.test]
command = [
    "cargo", "nextest", "run", "--color", "always",
]
need_stdout = true
```

When the tests pass I get to see nextest's highly-informative output (in colour, even though it doesn't show up here):
```

    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.01s
    Starting 1 test across 1 binary (run ID: f68cbdcf-7b7a-4af8-a5f6-01a0005a7d89, nextest profile: default)
        PASS [   0.003s] rust tests::it_works
------------
     Summary [   0.003s] 1 test run: 1 passed, 0 skipped
```

 but when the tests fail, I get the very unhelpful and disapponting

```
 1  failed: tests::it_is_broken
 no output
```
Can `bacon` be made to work with `cargo nextest`?

### PR DESCRIPTION
**Pull request by Canop**
Fix #196

To try it, define a job like this:

```TOML
[jobs.nextest]
command = ["cargo", "nextest", "run", "--color", "always", "--hide-progress-bar", "--failure-output", "final"]
need_stdout = true
analyzer = "nextest"
```

It's currently among default jobs but I'm unsure whether to keep it there.

### CODE REVIEW

**Comment by DragonDev1906** [comment]
Two suggestions for improvement:
- Bacon currently strips out the crate name (purple in the screenshot). In many cases this is fine, but with integration tests (see the `bacon::line_analysis` test you loose relevant information that is only visible in the detailed output (at least with panics+asserts). This is worse for workspace projects, which have multiple crates in it, thus making it harder to find the where the failing test is.
- This one is probably subjective, but I think the output should keep the coloring schema of `<crate> <package>::<testname>`. Personally I find it easier to read [^1] than when the entire line (except for the start) is bold white. Even though the bold white matches the format of `bacon test`

2024-10-01-112441_1015x705_scrot

### Something else I noticed while testing
`bacon test` doesn't run/show the `line_analysis` integration test of bacon itself (added a `todo!()` in it), while `bacon nextest` does.

[^1]: Especially when the crate name is also shown

**Comment by Canop** [comment]
Thanks for your suggestions. They look good.

Regarding doctests, last time I checked nextest was just unable to run them.

**Comment by DragonDev1906** [comment]
> Regarding doctests, last time I checked nextest was just unable to run them.

Ah, that would explain the time difference of course

**Comment by Canop** [comment]
@DragonDev1906 

> bacon test doesn't run/show the line_analysis integration test of bacon itself (added a todo!() in it), while bacon nextest does.

I can't reproduce this

**Comment by DragonDev1906** [comment]
> I can't reproduce this

That's weird. Here is what I did:
Branch: `nextest`
Commit: 4bdfb2b
Cargo version: `cargo 1.79.0 (ffa9cf99a 2024-06-03)`
Rustc version: `rustc 1.79.0 (129f3b996 2024-06-10)`
Build command: `cargo build --release`
Bacon command: `./target/release/bacon test`

Changed files (mainly the TODOs, the rest was rustfmt):
```diff
diff --git a/src/analysis/nextest_analyzer.rs b/src/analysis/nextest_analyzer.rs
index 3510aef..cb37ef0 100644
--- a/src/analysis/nextest_analyzer.rs
+++ b/src/analysis/nextest_analyzer.rs
@@ -1,8 +1,4 @@
-use {
-    super::*,
-    crate::*,
-    lazy_regex::*,
-};
+use {super::*, crate::*, lazy_regex::*};

 const CSI_TITLE: &str = "\u{1b}[35;1m";
 const CSI_PASS: &str = "\u{1b}[32;1m";
@@ -66,7 +62,11 @@ fn extract_key_after_crate_name(mut strings: std::slice::Iter<'_, TString>) -> O
     if strings.next().is_some() {
         return None;
     }
-    if key.is_empty() { None } else { Some(key) }
+    if key.is_empty() {
+        None
+    } else {
+        Some(key)
+    }
 }

 fn is_error_test_run_failed(content: &TLine) -> bool {
@@ -142,6 +142,7 @@ fn test_title_key() {
         title_key(&content),
         Some("analysis::nextest_analyzer::test_as_test_result".to_string())
     );
+    todo!()
 }

 #[test]
diff --git a/tests/line_analysis.rs b/tests/line_analysis.rs
index d6a5bb2..bc98ca1 100644
--- a/tests/line_analysis.rs
+++ b/tests/line_analysis.rs
@@ -29,4 +29,5 @@ fn line_analysis() {
             }
         }
     }
+    todo!()
 }
```

~/.config/bacon/prefs.toml
```toml
show_changes_count = true
[export]
enabled = false
path = ".bacon-locations"
line_format = "{kind} {path}:{line}:{column} {message}"
[keybindings]
n = "job:nextest"
```

Output:
2024-10-01-164413_970x479_scrot
2024-10-01-164431_955x477_scrot

In case it's relevant: Here is the Cargo.lock (same happens when I delete the Cargo.lock and recompile):
[Cargo.lock.txt](https://github.com/user-attachments/files/17211550/Cargo.lock.txt)

**Comment by adamchalmers** [comment]
Is there any way to pass `--package my-lib`  to `cargo nextest run` with this default job? Or a way to parameterize my nextest job to allow it?

(I know I can pass filters to nextest via `--` and they get passed nicely how I expect, but I wonder about arguments to nextest itself)

**Comment by DragonDev1906** [comment]
> Is there any way to pass --package my-lib to cargo nextest run with this default job? Or a way to parameterize my nextest job to allow it?

You should be able to do so via the bacon.toml:
```toml
[jobs.nextest]
command = [
    "cargo",
    "nextest",
    "run",
    "--color",
    "always",
    "--hide-progress-bar",
    "--failure-output",
    "final",
    "--",
    "--package",
    "my-lib"
]
need_stdout = true
analyzer = "nextest"
```

**Comment by Canop** [comment]
I had a try at splitting the module and function parts of a test key:
image

This might be a little too much colored. Not sure whether I'll opt for this or just for bold for the function name.

**Comment by adamchalmers** [comment]
@DragonDev1906 Yeah that's what I ended up doing, though I was trying to find a solution where I could supply the package name in the command line (i.e. `bacon nextest -p my-lib`, but of course, that flag gets passed to `bacon` not to `nextest`. It's fine though.

**Comment by Canop** [comment]
@adamchalmers you can provide arguments to the command after `--` (see https://dystroy.org/bacon/cookbook/#variable-arguments). But we're probably going out of topic there.

**Comment by Canop** [comment]
In my tests, I do have stderr. Can you please wrap up a complete self-contained example ?

**Comment by adamchalmers** [comment]
Ah, I tried to package up a repro, and discovered my problem: I was using normal `bacon` from my path, not the bacon from source. Seems to work now! I'll test this more tomorrow, now that I've aliased `bacon` to use my build from this branch.

**Comment by Canop** [comment]
I just pushed a commit to include the branch name in the version.
This makes it possible to check you're on the right branch by hitting '?' which brings the help screen:

image

Please do the check before submitting a problem.

**Comment by Canop** [comment]
I'm merging this. Problems, if any, will go to new issues.

I won't do a versionned release immediately, so there's still time to test and test. I'll also merge in a few other interesting features I have in progress.

And then... I think I'll release as a 3.0.

**Pull request merged**
