### PR TITLE
Add option to disable help line

### PR DESCRIPTION
**Pull request by danielwolbach**
Add an option to disable the help line.

This can either be done by using `--no-help-line` or modifying `prefs.toml`:

```
# .config/bacon/prefs.toml
help_line = false
```

The argument `--help-line` overwrites this setting.

The help line doesn't really serve a purpose for me, as it really doesn't show a lot of information and I didn't like it being constantly there.

### CODE REVIEW

**Comment by Canop** [comment]
Sorry for the delay, I won't forget to evaluate this PR, but it probably  won't be before next week.

**Comment by Canop** [comment]
Now, the question I ask myself is: "Is this option useful enough to justify cluttering the launch options" ?

Other opinions welcome.

**Comment by danielwolbach** [comment]
I would appreciate the cleaner look, as I usually work with a lot of Tmux panes and having less visual clutter always helps. However, I am of course aware that this is purely aesthetic and not necessarily _reasonable_ enough for maintaining additional settings.

**Comment by Canop** [comment]
I merged it. No guarantee it stays but right now there aren't too many options so it's OK.

**Pull request merged**
