### PR TITLE
fix either raw/standard output not rewrapped

### LINKED ISSUE #234: Trying to wrap or unwrap lines in raw mode does nothing
On macOS, when I use `toggle-raw-output` to go back to the original verbose test output, I can't wrap or unwrap lines.

Steps to reproduce:
1. Run a test with long lines and failures
2. Wait for it to finish, which goes to the fails summary screen
3. Do `toggle-raw-output` (I use my own key binding for this)
4. Try to wrap or unwrap lines

Expected outcome:
Line wrapping changes

Actual outcome:
Line wrapping does not change

If raw mode ignored wrapping entirely, that would be consistent but annoying. Instead, raw mode won't unwrap-to-wrap or wrap-to-unwrap lines.

### PR DESCRIPTION
**Pull request by Canop**
Fix #234

### CODE REVIEW

**Comment by teor2345** [comment]
Thanks for the quick fix, but this doesn't seem to quite work the way I expect.

When I set `wrap = false` in `prefs.toml`, no wrapping happens at all, either in the initial `test` screen, or the `fails` result summary screen, regardless of how many times I press `w`. I expected that `w` would cause wrapping (and then unwrapping when pressed again), in both screens.

When I set `wrap = true` in `prefs.toml`, wrapping happens in the `fails` screen, and correctly unwraps on `w`. This works as expected. But the raw output starts unwrapped, and doesn't wrap on `w`.

Is there another way of switching back to the detailed output that also does wrapping? Because maybe I'm expecting the wrong things from raw mode. If that's the case, then the only bug is disabling wrapping entirely in the `fails` screen when `wrap = false`.

**Comment by Canop** [comment]
You're right. I was too fast in pushing this PR.

**Comment by Canop** [comment]
I think I fixed the fix.

**Comment by teor2345** [comment]
Sory for the delay, yes this works as expected!

**Pull request merged**
