### PR TITLE
fix: :bug: Fix scroll in terminals on Windows

### PR DESCRIPTION
**Pull request by Adham-A**
#153

### CODE REVIEW

**Comment by Canop** [comment]
When you enable mouse capture in a program, you must disable it on end, or the terminal ends in a bad state.

Similar modifications are done then removed in `cli.rs` (look at `w.queue(cursor::Hide)?;` and `w.queue(cursor::Show)?;`). That's where you must move mouse enabling and disabling (and use `queue`, not `execute`, as for others).

**Comment by Adham-A** [comment]
I now enable and disable in `cli.rs`,
I added `#[cfg(windows)]` in enabling and disabling, as well as in imports, since it showed unused warnings on Linux,

Something else to change/refactor ?

**Comment by Canop** [comment]
> Something else to change/refactor ?

Nothing that I see right now. If you tested it seriously on Windows I'll take it from here.

**Comment by Adham-A** [comment]
For information: I tested on Windows 10

**Pull request merged**
