### PR TITLE
Add net feature of tokio for enable_io

### PR DESCRIPTION
**Pull request by Stargateur**
Closes https://github.com/Canop/bacon/issues/87

Look bacon run ok on windows with this.

### CODE REVIEW

**Comment by Canop** [comment]
@Stargateur Did you check it fixes 87 on Windows ?

**Comment by Stargateur** [comment]
Yes, it's compile and look ok. run some command, only thing weird is I can't open help menu with '?' but 'h' work, I think it's may be azerty keyboard thing. But all job work, clippy test etc

**Comment by Canop** [comment]
The '?' key problem must be unrelated

**Comment by Canop** [comment]
Thanks a lot @Stargateur

**Pull request merged**
