### PR TITLE
search input

### PR DESCRIPTION
**Pull request by Canop**
Focus the search input with <kbd>/</kbd>.

When search input is focused, unfocus it with either :
* <kbd>esc</kbd>,  cancelling it
* <kbd>enter</kbd>,  freezing it

Navigate between matches with `tab` and `alt-tab`.

You can define other shortcuts, eg

```
[keybindings]
n = "next-match"
shift-n = "previous-match"
```

But those ones aren't ideal: they conflict with the <kbd>n</kbd> being currently bound to nextest, and they can't be used when the search is focused (you can hit <kbd>enter</kbd> before navigating but then you'll have to hit <kbd>/</kbd> again if you want to add to the pattern).

#224

### CODE REVIEW

**Comment by Canop** [comment]
I'm still not sure of what would be best: filtering items or lines. Current version is filtering lines but it's probable items would be better.

**Comment by crumblingstatue** [comment]
> I don't think a filtering logic is the right one, there, I'll rather make it find and focus the right parts in the output

I agree

> enable navigating between matches with tab and alt-tab.

I don't think alt-tab is a good idea, as it's a standard key combo for switching windows, making the terminal window unfocus.

The `less` pager uses `n` and `shift+n` for next/previous.

**Comment by Canop** [comment]
I think I have the right behavior now.

I still need to cover the case of a search match spanning over the line wrapping location, but the rest seems OK.

**Comment by Jirubizu** [comment]
Had a quick view at MR (currently only have my phone available) unless I missed it. This is just doing basic string searching right? So for example regex patterns would not work?

Btw thank you for getting around to doing this feature!

**Comment by Canop** [comment]
> This is just doing basic string searching right? So for example regex patterns would not work?

Correct.

**Comment by crumblingstatue** [comment]
I think it would be nice to update the contextual help when in search mode.
The standard `Hit s to toggle summary mode, ? for help, w to not wrap lines, p to pause, q to quit` does not apply, since all the keys are captured by the search bar.
It could instead show `Hit Tab for next result, Shift+Tab for previous`.

**Comment by Canop** [comment]
I wondered about that, then thought everybody would think about those. But I'll add them.

**Comment by Canop** [comment]
Done
image

**Comment by Canop** [comment]
I missed something in your remark. It's exact that some keyboard shortcut shouldn't be mentioned when the input is focused because they wouldn't work...

**Comment by crumblingstatue** [comment]
The search offsets are wrong in summary mode. Hopefully it's not too hard to make it work properly for both normal and summary mode.

**Comment by crumblingstatue** [comment]
One possible cool improvement would be to show the number of results, and also say "no results" if there are no results.
The bottom row is pretty busy, but maybe it could be added to the top indicator row?
image

**Comment by Canop** [comment]
image

**Comment by crumblingstatue** [comment]
Thank you, it seems to be working well!
Although maybe it would make it more clear to display "No results" or similar when there are no results for the search input, rather than display nothing.

**Comment by crumblingstatue** [comment]
Thank you, the feature seems to be working well, but I'll do some more testing today. It seems to be ready for the most part though.

**Comment by Canop** [comment]
I'll merge it. Related fixes and improvements, if necessary, will come in later PR.

**Comment by c-git** [comment]
This feature is really cool.

**Pull request merged**
